log:
  level: trace
identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/identity.default.schema.json
selfservice:
  default_browser_return_url: http://127.0.0.1:9999/
  flows:
    registration:
      enabled: true
      ui_url: http://127.0.0.1:9999/registration
