name: auto-approver
run-name: CI for approving PRs

on:
  push:
    branches:
      - "renovate/**"
      - "automated-update-charm-libs"

jobs:
  auto-approve:
    name: Auto-approve and merge pull request
    uses: canonical/identity-team/.github/workflows/pr-auto-approval.yaml@356ff61bd885e4147cc22c6eea64e4d806c889da # v1.11.3
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
