name: ci
run-name: CI for ${{ github.sha }} on ${{ github.ref_name }}

on:
   workflow_dispatch:
   push:
     branches:
     - "main"
     - "release-**"
     - "track/**"
     paths-ignore:
     - "terraform/**"
   pull_request:
     branches:
     - "*"
     paths-ignore:
     - "terraform/**"

jobs:
  tests:
    name: CI
    uses: canonical/identity-team/.github/workflows/charm-pull-request.yaml@add-multi-arch-parameter
    with:
      container-name: "kratos"
      # TODO: Re-enable when arm64 build is complete in ccc-hub
      use-charmcraftcache: false
      node-size: large
      multi-arch: true
