name: ci
run-name: CI for ${{ github.sha }} on ${{ github.ref_name }}

on:
   workflow_dispatch:
   push:
     branches:
     - "main"
     - "release-**"
     - "track/**"
     paths-ignore:
     - "terraform/**"
   pull_request:
     branches:
     - "*"
     paths-ignore:
     - "terraform/**"

jobs:
  tests:
    name: CI
    uses: canonical/identity-team/.github/workflows/charm-pull-request.yaml@15ddf22d348a6ca76a7d82dc702c71ab083f9a80 # v1.13.0
    with:
      container-name: "kratos"
      use-charmcraftcache: true
      node-size: large
