name: ci
run-name: CI for ${{ github.sha }} on ${{ github.ref_name }}

on:
   workflow_dispatch:
   push:
     branches:
     - "main"
     - "release-**"
     - "track/**"
     paths-ignore:
     - "terraform/**"
   pull_request:
     branches:
     - "*"
     paths-ignore:
     - "terraform/**"

jobs:
  tests:
    name: CI
    uses: canonical/identity-team/.github/workflows/charm-pull-request.yaml@84c2f3e8f31c76602dd3ccceff9b8231316af615 # v1.11.1
    with:
      container-name: "kratos"
      use-charmcraftcache: true
      node-size: large
