name: On Schedule
on:
  schedule:
    - cron: '0 8 * * MON'

jobs:
  update-charm-libs:
    name: Update Charm Libraries
    uses: canonical/identity-team/.github/workflows/charm-libs-update.yaml@5830f3e6723de07cb5b7ccb6c84031d8b2964c62 # v1.11.4
    secrets:
      CHARMCRAFT_CREDENTIALS: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

  tests:
    name: CI
    uses: canonical/identity-team/.github/workflows/charm-pull-request.yaml@5830f3e6723de07cb5b7ccb6c84031d8b2964c62 # v1.11.4
    with:
      container-name: "kratos"
      use-charmcraftcache: true
