name: release

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - "track/**"

permissions:
    contents: write
    pull-requests: write

jobs:
  release:
      name: release
      uses: canonical/identity-team/.github/workflows/charm-release.yaml@b5428d226e364de1c5ad601c1ec27c333f489d1d # v1.16.2
      secrets:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
