name: release

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - "track/**"

permissions:
    contents: write
    pull-requests: write

jobs:
  release:
      name: release
      uses: canonical/identity-team/.github/workflows/charm-release.yaml@732520bcf8f04f777f44d1c3677e7a89f7ce9ab6 # v1.11.0
      secrets:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
