name: Tests
on:
  workflow_dispatch:
  workflow_call:

jobs:
  unit-test:
    name: Unit tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install dependencies
        run: python -m pip install tox

      - name: Run tests
        run: tox -e unit

  integration-test-microk8s:
    name: Integration tests (microk8s)
    runs-on: ubuntu-24.04
    needs:
      - unit-test
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          channel: 1.28-strict/stable
          juju-channel: 3.4/stable
          microk8s-addons: "hostpath-storage metallb:10.64.140.43-10.64.140.49"

      - name: Run integration tests
        # set a predictable model name so it can be consumed by charm-logdump-action
        run: tox -e integration -- --model testing

      - name: Get contexts
        run: kubectl config view
        if: failure()

      - name: Get juju status
        run: juju status --relations
        if: failure()

      - name: Get juju logs
        run: juju debug-log --replay --include unit-kratos-0
        if: failure()

      - name: Get kratos container logs
        run: kubectl logs kratos-0 -c kratos -n testing
        if: failure()

      # Hack to overcome lack of tools (cat, tar) in the workload container
      - name: Get kratos config file
        run: |
          juju ssh kratos/0 "PYTHONPATH=agents/unit-kratos-0/charm/venv/ python3 -c '
          from ops import pebble
          p = pebble.Client(\"/charm/containers/kratos/pebble.socket\")
          f = p.pull(\"/etc/config/kratos/kratos.yaml\")
          print(f.read())
          '"
        if: failure()
