name: TODO Scan After PR Merge

on:
  push:
    branches:
      - main

jobs:
  todo-to-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0

      - name: TODOs to Issues
        uses: alstr/todo-to-issue-action@37bb7b56e58569ef273b60678048030a7f0c261a # v5
        with:
          IGNORE: "lib/charms/(?!kratos/).*"
