name: TODO Scan After PR Merge

on:
  push:
    branches:
      - main

jobs:
  todo-to-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0

      - name: TODOs to Issues
        uses: alstr/todo-to-issue-action@64aca8fda7023259aada83ba44ad988c4c443657 # v5
        with:
          IGNORE: "lib/charms/(?!kratos/).*"
