# reusable workflow for checking library versions and opening PRs to bump
name: Update Charm Libraries

on:
  workflow_dispatch:

jobs:
  update-charm-libs:
    name: Update Charm Libraries
    uses: canonical/identity-team/.github/workflows/charm-libs-update.yaml@1bf335af1d939c8543e53d376dd49d79126c2cd3 # v1.15.0
    secrets:
      CHARMCRAFT_CREDENTIALS: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
