# reusable workflow for checking library versions and opening PRs to bump
name: Update Charm Libraries

on:
  workflow_dispatch:

jobs:
  update-charm-libs:
    name: Update Charm Libraries
    uses: canonical/identity-team/.github/workflows/charm-libs-update.yaml@732520bcf8f04f777f44d1c3677e7a89f7ce9ab6 # v1.11.0
    secrets:
      CHARMCRAFT_CREDENTIALS: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
