# reusable workflow for checking library versions and opening PRs to bump
name: Update Charm Libraries

on:
  workflow_dispatch:

jobs:
  update-charm-libs:
    name: Update Charm Libraries
    uses: canonical/identity-team/.github/workflows/charm-libs-update.yaml@b5070d98993fa72f429f4fdf8010f6f9a94eb4e0 # v1.14.2
    secrets:
      CHARMCRAFT_CREDENTIALS: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
